### ISSUE TITLE
Swarm Listener not configuring proxy

### ISSUE THREAD

**Issue by lhenry7** [vfarcic/docker-flow-swarm-listener#19]
This will be very similar to issue #2 . On docker 1.13, I created proxy overlay network:
docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
daee4250c827        bridge              bridge              local
43f46b6fb031        docker_gwbridge     bridge              local
18b85b1ed3b2        host                host                local
j1mmkw5jyijq        ingress             overlay             swarm
3d7d5962e86d        none                null                local
lajji86c4z50        proxy               overlay             swarm
alxoxmr3grmg        swarmnet            overlay             swarm

Then, I've started swarm listener using:
docker service create --name swarm-listener \
>     --network proxy \
>     --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
>     -e DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure \
>     -e DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove \
>     --constraint 'node.role==manager' \
>     vfarcic/docker-flow-swarm-listener

and proxy using:
 docker service create --name proxy \
> -p 80:80 \
> -p 443:443 \
> --network proxy \
>  --replicas 2 \
> -e MODE=swarm \
> -e LISTENER_ADDRESS=swarm-listener

Then after starting a new service using docker stack create:
version:  '3'
services:

  app:
    image: dsg.infra/application-service
    labels:
     - com.df.notify=true
     - com.df.distribute=true
     - com.df.servicePath=/
     - com.df.serviceDomain=dev.shouldcost.corporate.ge.com
     - com.df.port=80
    environment:
     - JSON=shouldcost/files/dev_chef_files.zip
     - HEALTHCHK=DRUPAL
    volumes:
     - /shouldcost-dev-files:/shouldcost-dev-files
    networks:
     - proxy
     - swarmnet
    deploy:
      replicas: 2
      placement:
        constraints: [node.role != manager]
      resources:
        limits:
          memory: 8G
networks:
  proxy:
    external: true
  swarmnet:
    external: true

and then docker service update --publish-add 1234:8080 proxy:
 curl localhost:1234/v1/docker-flow-proxy/config
global
    pidfile /var/run/haproxy.pid

defaults
    mode    http
    balance roundrobin

    option  dontlognull
    option  dontlog-normal
    option  forwardfor
    option  redispatch

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout http-request 5s
    timeout http-keep-alive 15s

    stats enable
    stats refresh 30s
    stats realm Strictly\ Private
    stats auth admin:admin
    stats uri /admin?stats

frontend dummy-fe
    bind *:80
    bind *:443
    mode http
    option http-server-close
    acl url_dummy path_beg /dummy
    use_backend dummy-be if url_dummy

backend dummy-be
    mode http
    server dummy 1.1.1.1:1111 check

the logs are this:
for proxy:
 docker logs -f dd9ea9ae1bae
2017/02/10 14:21:44 Starting HAProxy
2017/02/10 14:21:44 A request was sent to the Swarm listener running on http://swarm-listener:8080. The proxy will be reconfigured soon.
2017/02/10 14:21:44 Starting "Docker Flow: Proxy"
2017/02/10 14:21:47 Processing request /v1/docker-flow-proxy/certs
2017/02/10 15:09:00 Processing request /v1/docker-flow-proxy/config

for listener:
docker logs -f 4050068b4188
2017/02/10 13:49:18 Starting Docker Flow: Swarm Listener
2017/02/10 13:49:18 Starting iterations

but no automatic configuration.  What am I missing?

**Comment by vfarcic** [comment]
Swarm listener is processing only services with *service* label `com.df.notify`. The problem is most likely in your compose file. You're using container (NOT service) labels. Can you move your labels under the `deploy` section of your YAML file and try again?

**Comment by lhenry7** [comment]
Outstanding! That did the trick. First time using the Version 3 docker-compose.

And now interestingly enough, the 2nd half of issue #2. I want to run multiple domains, each with its own ssl certs. I also prefer to mount an NFS volume where the certs can be found. Can you walk through the steps to configure services in this way? Assuming I can mount a volume containing 10-20 certs, what do I need to do to support multiple domains+certs?

**Comment by vfarcic** [comment]
Are those domains using different services (one service > one domain) or multiple domains with the same service (one service > multiple domains)?

You'll see a note in the [Put Certificatate](https://proxy.dockerflow.com/usage/#put-certificate) section of the documentation (near the end of it).

*it is recommended to mount `/certs` directory to a network drive and thus ensure that certs are preserved in case of a failure.*

**Comment by lhenry7** [comment]
Right, it would be one domain -> multiple services(some http some https) -> one cert _per domain_ (multiple domains matching this relationship).

I see the past discussion about this, so assuming I add 'volumes - /host/cert/folder:/certs', the proxy will have access to all of the certs, and then is there a way to map on the initial configure domain to cert, or must it be some kine of reconfigure cmd to map the cert to the domain? As you can see this isn't coming together for me, sorry for the confusion.

**Comment by vfarcic** [comment]
The proxy does have access to all the certificates but the handshake between a browser and the proxy will be done with a certificate that matches the domain.

You can bind multiple certificates on port 443 (sent with [Put Certificate](https://proxy.dockerflow.com/usage/#put-certificate) requests). HAProxy will respond with the certificate based on the caller's request. The only requirement is that the hostname from the request matches the hostname from the certificate and that a browser supports SNI (almost all browsers do).

Can you try to add two certificates to the proxy and test it through domains of those certificates?

**Comment by lhenry7** [comment]
Thanks for the feedback. I'm rethinking how I want to handle SSL termination in the first place, so for now I'll try a few things and open a new issue if I run into anything specific.

I want to close this issue since you've answered the initial question, but I have just one more question around handling domain/services on multiple http ports. I'm trying to define services for the same domain/path, using multiple frontend/backend ports. So service,domain/path,port 80 and then either the same or a different service,domain/path,port 443. Currently the first one wins and the second is ignored. Can the acl's be made to include matching the src_port to the service port?

Larry Henry

  *   Staff Infrastructure Architect
·         Staff Infrastructure Architect
·         Staff Infrastructure Architect
Staff Infrastructure Architect -  Digital Strategy Group  GE Digital

T 734 641 2415
F 734 727 5420
M 734 502 9855
Larry.Henry@ge.com<mailto:Larry.Henry@ge.com>

Grace Lake Corporate Center
One Village Center Drive
Van Buren Twp, Michigan 48111
General Electric Company

GE imagination at work

**Comment by vfarcic** [comment]
@lhenry7 At the moment, `src_port` is not used for ACLs. That can be added. Can you clarify whether you'd like to match HAProxy `src_port` (port of the client) or `dest_port` (destination port, equivalent to `port` from the request you're sending to the proxy)? They are sometimes (but not always), the same. In either case, can you open an issue? I think it would be easier to track it separatelly. Adding this feature should be a very quick thing to do so you can expect it soon.
