### ISSUE TITLE
Add Prometheus integration

### ISSUE THREAD

**Issue by vfarcic** [vfarcic/docker-flow-swarm-listener#23]

**Comment by alexsandro-xpt** [comment]
+1

**Comment by vfarcic** [comment]
The integration is already finished. The only thing missing is documentation. I hope to have it done in two weeks.

**Comment by alexsandro-xpt** [comment]
Do not forget to tell us.

**Comment by vfarcic** [comment]
It's done :). You can find the docs in http://monitor.dockerflow.com/ .

The objective is to create a self-healing system and there's still a lot to be done. The part that is in charge of monitoring and alerting is done.

Can you please try it out and let me know what you think. Any feedback is welcome. PRs even more :)
