### ISSUE TITLE
Need a way to run multiple listeners in swarm (mode) to avoid SPOF.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [vfarcic/docker-flow-swarm-listener#25]
A common setup with `prod`, `dev`, etc. environments requires the ability to run multiple swarm listeners.

In such a setup, each swarm-listener will be connected to a separate proxy and set of backend services, but because the docker socket exposes all information, it will notify the proxy of irrelevant containers.

The docker-native fix for this would probably be to filter on labels.

**Comment by s4s0l** [comment]
You really keep prod and dev in one swarm cluster?!?

**Comment by vfarcic** [comment]
@alexanderkjeldaas I just added an environment variable `DF_NOTIFY_LABEL`. It's default value is `com.df.notify`. If you change it to something else (e.g. `com.df.notifyDev`). You can use it to distinguish which services should be notified with one or the other `swarm-listener` (or both).

Can you please try it out and let me know whether it fixes this issue. Please make sure to use the release `1.25`.

I must stress that @s4s0l is correct. Even though you can use the environment variable `DF_NOTIFY_LABEL` to tell each `swarm-listener` which services should send notification requests, it is a bad practice to keep prod and dev in the same cluster.

**Comment by alexanderkjeldaas** [comment]
@vfarcic why is it bad practice to keep prod and dev in the same cluster?

To me it obviously is not, given that the swarm mode is tied into DNS and keeping separate clusters implies a *policy* on not being able to use any public DNS shared between the two environments.

But it's fairly irrelevant whether it is good practice or not - I think we can agree that docker flow shouldn't require a particular policy.

**Comment by vfarcic** [comment]
@alexanderkjeldaas The reason for such a statement about separation is more related to resources and human errors. For example, a test service might have a memory leak that will affect production services running inside the same cluster.

However, as you said, it's not DFPs job to decide whether there should be a separation or not.

Please let me know if the environment variable `DF_NOTIFY_LABEL` solves your problem.

**Comment by alexanderkjeldaas** [comment]
It seems to solve the problem, but this requires labels to be specified as an array, because I need syntax like:

```
        - "com.df.notify${STACK_NAME}=true"
```

The key part of a key/value set is not going through the docker-compose environment variable expansion stage.

**Comment by vfarcic** [comment]
@alexanderkjeldaas I probably missunderstood your requirements. Let me explain the idea that I implemented.

swarm-listener-1: env. var `DF_NOTIFY_LABEL=com.df.notify1`
swarm-listener-2: env. var `DF_NOTIFY_LABEL=com.df.notify2`

service-1: label `com.df.notify1=true`
service-2: label `com.df.notify2=true`
service-2: labels `com.df.notify1=true com.df.notify2=true`

With such a setting, `swarm-listener-1` would send reconfigure notifications to `service-1` and `service-3` while `swarm-listener-2` would send reconfigure notifications to  `service-2` and `service-3`. Each of those listeners could have a different address of a proxy.

As a result, one proxy would get `service-1` and `service-3` while the other would have `service-2` and `service-3`.

Can you please let me know if that solves your problem or I misunderstood the use case?

**Comment by alexanderkjeldaas** [comment]
My problem *is* solved, it's just that the name of the label is the variable, so key/value syntax can't be used.

If the value of the label was used instead, then it would be

swarm-listener-1: env. var DF_NOTIFY_LABEL=foo
swarm-listener-2: env. var DF_NOTIFY_LABEL=bar

service-1: label com.df.notify=foo
service-2: label com.df.notify=bar
service-2: labels com.df.notify=foo,bar

which conveys the same information, but allows for variable expansion in the `docker-compose.yml` file.

**Comment by vfarcic** [comment]
@alexanderkjeldaas That is a good idea. Would you mind opening a new issue. That way we can start fresh, treat it as an improvement over the existing feature, and track it more easily.
