### ISSUE TITLE
Continous Memory consumption over time

### ISSUE THREAD

**Issue by Thomas0c** [vfarcic/docker-flow-swarm-listener#3]
After running `swarm-listener` for a few days I'm now seeing that the container is consuming more and more memory over time, which then gets resolved as soon as service is restarted, e.g. by adding an env variable: `docker service update --env-add test=false swarm-listener`.

See graph below, which shows memory over time 
![swarm-listener](https://cloud.githubusercontent.com/assets/8699937/20224629/5b6c3aba-a80d-11e6-91db-52620c9a00d5.png)

The sudden drop in memory happened right after restarting the service. Not sure if this is expected, or if there's anything I can do to limit the memory consumption?

This is tested on an AWS EC2 instance `t2.small`.

**Comment by vfarcic** [comment]
That is not the expected behavior. I'll profile the service and fix the memory leak soon.

**Comment by vfarcic** [comment]
I think that the bug is fixed. It was a combination of a bug in the Docker client that manifests itself only if compiled with Go 1.6. Or, at least I think that was the problem.

I made a new release 0.5 and monitored it for one hour. So far memory does not increase. I'll leave it overnight and double check the results tomorrow.

Can you test it as well and let me know how it behaves?

**Comment by Thomas0c** [comment]
Yes. Just updated the service and will report back by end of weekend. Thanks for the swift response and update!

**Comment by Thomas0c** [comment]
Using `0.6`, which seemingly was the latest, seems to have fixed the problem - see below.
<img width="799" alt="screen shot 2016-11-12 at 2 46 07 pm" src="https://cloud.githubusercontent.com/assets/8699937/20240477/0e7e8976-a8e7-11e6-85a5-64c0ec1c4df9.png">

Thanks again for the quick response and action.

**Comment by vfarcic** [comment]
Yeah. I made 0.6 shortly after 0.5. It's only a minor improvement.

Thank you for confirming that it works.
