### ISSUE TITLE
Ping endpoint for healthcheck

### ISSUE THREAD

**Issue by chrisns** [vfarcic/docker-flow-swarm-listener#35]
Please can there be a handler for `/v1/docker-flow-proxy/ping` similar to DFP so that I can healthcheck the listener?
At the minute I'm using `wget -q -O /dev/null localhost:8080/v1/docker-flow-swarm-listener/get-services || exit 1` but that doesn't really feel right
Thanks

**Comment by vfarcic** [comment]
It's available from the [release 17.10.07-15](https://github.com/vfarcic/docker-flow-swarm-listener/releases/tag/17.10.07-15).

Please try it out and let me know if it works as expected.
