### ISSUE TITLE
highly available DFSL ?

### ISSUE THREAD

**Issue by dsw9742** [vfarcic/docker-flow-swarm-listener#45]
This is a question about DFSL as a SPOF.

In a [Docker Swarm auto setup](http://proxy.dockerflow.com/swarm-mode-auto/), I see there may be multiple DFP instances, but it looks like there is only ever a single DFSL instance.

What happens if DFSL goes down and a targeted Docker Swarm service starts/updates/terminates before DFSL restarts?

I am assuming DFSL is pulling Docker Events from the distributed Swarm Raft logs, in which case I am under the impression DFSL would observe, reconcile, and react to the service changes that occurred while it was down, but I have been unable to locate any documentation stating that, and I just want to be sure that is indeed how it works.

Would love any insight into how this scenario would play out in a live environment.

Thanks!

**Comment by vfarcic** [comment]
If DFSL fails, Swarm will reschedule it and it'll be running again soon afterwards. When a new replica of DFSL is created, it retrieves the info about all the services in the cluster and sends it to DFP. On the other end, DFP will receive the info sent by DFSL and create a new config. So, if during that second DFSL was down, a new service was created, it would still reach DFP.

Please let me know whether that answers your question.

**Comment by dsw9742** [comment]
Answered 100%. Thanks Viktor!
