### ISSUE TITLE
Queue Based System Refactor

### ISSUE THREAD

**Issue by thomasjpfan** [vfarcic/docker-flow-swarm-listener#47]
While working on #46, I find myself implementing a queue based system for docker node events. I would like to refactor the services piece to use queues as well. The concept is as follows:

The Docker events api outputs of stream of node or service events. These events can be filtered if there is too much noise (as in the case of node events). Afterwards, the `eventID` along with the action, (`create`, `update`, `remove`), will be placed on an `eventQueue`. A `Translator` goroutine will be watching this `eventQueue` to translate the `eventID` into a `Node` or `Service` object. This object will be place on an `nodeQueue` or a `serviceQueue`. Finally, a `Notifier` goroutine watching the `nodeQueue` or `serviceQueue` will be pick up the `Node` or `Service` and send out notifications.

The `Translator` will cache the relationship between ID and name just for the `remove` events. In this case the docker api would have no information about the service since it was removed, and we wish to send the serviceName when a service is removed.

The services code in its current state may lead to an incorrect state from latency issues. For example, in the situation where:

1. Remove event first then a create event.
2. The latency of the create notification is 100ms.
3. The latency of the remove notification is 500ms.

The listener would receive the create notification first, and then the remove notification, which would lead to the listener thinking the service is down. 

This queues system makes sure the order of notifications is consistent with the Events coming from the Docker events API.

**Comment by vfarcic** [comment]
That sounds great!

**Comment by thomasjpfan** [comment]
Two questions on the intended behavior of DFSL

1. When a label not prefixed by `com.df.` is added, updated, or removed, do you intend for DFSL to send out notifications? Currently, when non-prefixed labels are removed, notifications are sent out. I think DFSL should just ignore all labels not prefixed by `com.df.` besides `com.docker.stack.namespace`. 

2. When a service is scaled to zero replicas, DFSL does not send any notifications. For example, if a service starts at 2 replicas and scales to zero, a service like DFP will still route requests to it thinking there are still 2 replicas. Is this the intended behavior?

**Comment by vfarcic** [comment]
1. The intention is to send a notification whenever one of the `com.df.` labels is added/removed/updated. The assumption is that if one of the other labels changes, that action is not related to DFSL and there's no need to send notifications. If notifications are sent when non-prefixed labels are removed, it's an error and I think we should fix it.

2. Initially, I did not contemplate the case of zero replicas thinking that no one would scale to zero if there are requests still coming in. That would produce errors no matter whether DFP is configured with that service or not. In the meantime, DFSL grew beyond serving only DFP so we might want to send notifications when something is scaled to zero. As a side note, DFP doesn't care how many replicas there are. It forwards requests to Overlay and let it handle LB.

**Comment by thomasjpfan** [comment]
1. PR #48 fixes this issue. Only labels prefixed with `com.df.` are considered by DFSL. (And `com.docker.stack.namespace` to use with the `com.df.shortName` feature.)

2. I don't really think of scaling services to zero either, but [issue #35 from DFM](https://github.com/vfarcic/docker-flow-monitor/issues/35) got me to consider it. PR #48 will send out notifications with `replicas=0` for services that are scaled to zero.
