### ISSUE TITLE
build failing for service.go

### ISSUE THREAD

**Issue by vitor-caetano** [vfarcic/docker-flow-swarm-listener#5]
$ go build
# github.com/vfarcic/docker-flow-swarm-listener
./service.go:40: unknown types.ServiceListOptions field 'Filter' in struct literal

**Comment by vfarcic** [comment]
That's strange. I just deleted all the dependencies and built the binary without changing anything. Can you paste the output with the error?

**Comment by vitor-caetano** [comment]
This are the steps I use to reproduce:

$ which go
/usr/local/bin/go

$ go version
go version go1.7.4 darwin/amd64

$ go get -u github.com/vfarcic/docker-flow-swarm-listener
# github.com/vfarcic/docker-flow-swarm-listener
vfarcic/docker-flow-swarm-listener/service.go:40: unknown types.ServiceListOptions field 'Filter' in struct literal
 ...
The above also downloads github.com/docker/docker with the docker/docker/api/types/client.go with the following struct:

// ServiceListOptions holds parameters to list  services with.
type ServiceListOptions struct {
	Filters filters.Args
}

Hope this helps.

**Comment by vfarcic** [comment]
You're right. I'm not sure what happened (whether one of the libraries changed in the meantime or...). Anyways, it's fixed. Thanks for letting me know.
